### ISSUE TITLE
Tooltip sizing

### ISSUE THREAD

**Issue by tlatoza** [devuxd/SeeCodeRun#184]
Tooltips should grow to fit the size of the content. If the content exceeds the size of the viewport horizontally or vertically, the tooltip should add a scroll bar.

**Comment by luminaxster** [comment]
Current checklist:
1. In the browser, we inspected the element with id "editorTooltip"
2. We traced it back to code: [src\traceView\expression-data-explorer.js](https://github.com/tlatoza/SeeCodeRun/blob/master/src/traceView/expression-data-explorer.js#L46)
3. We should create a new branch from branch "rc01" called "issue184" to tackle this issue.
4. Start adding //todo: to communicate the ideas you have for solving some parts of the issue.
5. Open a pull request for the branch using "rc01" as the base. 
6. If you consider necessary, create additional branches so you can review each other approaches.
7. Ask me questions on Slack referencing lines of code from your branch(es)
8. Solve the issue =]
9. David's review =[
10. Pull request merging! (^__^)

**Comment by CollinMetzger** [comment]
Resolved*
