### ISSUE TITLE
Run icon in the seeCode.run logo looks like a clickable button rather than part of the logo

### ISSUE THREAD

**Issue by tlatoza** [devuxd/SeeCodeRun#215]

**Comment by luminaxster** [comment]
How about something among these lines:
![image](https://cloud.githubusercontent.com/assets/6577822/24512847/a836eaf0-153d-11e7-9f3d-4937b14a9133.png)

**Comment by tlatoza** [comment]
Seems reasonable.

**Comment by CollinMetzger** [comment]
The run icon is in fact a button and I personally agree with it's current function of opening up a new session. As far as renovating the logo I have pictured below a suggestion. I found a more complete magnifying glass that is native to HTML5 and an image of a man running from the original "material-icons" page at https://material.io/icons/ . I personally don't mind the currently implemented play button icon.

![icontest](https://user-images.githubusercontent.com/18721769/27755171-084bfe14-5dbc-11e7-8a57-020baa420423.png)

**Comment by tlatoza** [comment]
I like the new design. Using a person running seems less likely to be confused with a play button. One suggestion: perhaps try to change the vertical heights so that the magnifying glass and running icon are about the same height as the text portion.

**Comment by CollinMetzger** [comment]
Yes I completely agree that the alignment and font was off in my prototype
image. The final product would be aligned and sized more properly.
