### ISSUE TITLE
Running seeCode.run in an iFrame

### ISSUE THREAD

**Issue by tlatoza** [devuxd/SeeCodeRun#216]
Is it possible to run seeCode.run in an iFrame? At the moment, we seem to be getting an error message.

![image](https://cloud.githubusercontent.com/assets/1881771/24310839/d0354280-10a7-11e7-9bd2-04b8dc6e72c7.png)

**Comment by luminaxster** [comment]
Now, we are not recording window, document, or really long object values:
 https://seecode.run/#-KgUV-cQSpmmDPqBYMIe.

**Comment by tlatoza** [comment]
There are now errors that prevent seeCode.run from starting.

![image](https://cloud.githubusercontent.com/assets/1881771/24508082/69785e46-1530-11e7-93fc-76f47c1a35ab.png)

**Comment by luminaxster** [comment]
I think that could be a problem with the browser's cache.
![image](https://cloud.githubusercontent.com/assets/6577822/24508956/0ec3698e-1533-11e7-8f4a-ba307bd9264c.png)

**Comment by tlatoza** [comment]
Yup, that fixes it.
